spring:
  datasource:
    url: jdbc:mysql://localhost:3306/novacart_dev?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: novacart
    password: novacart

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt:
    secret: dev-super-secret-change-me-in-real-environments
    access-token-expiration-ms: 3600000
    refresh-token-expiration-ms: 604800000
  cors:
    allowed-origins: http://localhost:4200
