server:
  port: 8811
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/novacart_dev
    username: root
    password: Kripa@123
  mail:
    host: smtp.gmail.com
    port: 587
    username: novocartofficial@gmail.com
    password: ryci bjzx keqb xwah
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: dev-super-secret-change-me-in-real-environments
    access-token-expiration-ms: 3600000
    refresh-token-expiration-ms: 604800000
  cors:
    allowed-origins: http://localhost:4200
  mail:
    from: novocartofficial@gmail.com
  frontend:
    url: http://localhost:4200